# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# syntax=docker/dockerfile:1

# Use official Python runtime
FROM python:3.11-slim

# Set working directory
WORKDIR /app

# Install build dependencies
RUN apt-get update \
    && apt-get install -y --no-install-recommends build-essential \
    && rm -rf /var/lib/apt/lists/*

# Copy project files
COPY . .

# Install Python dependencies with S3 support
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -e .[s3]

# Expose ports
EXPOSE 8080

ENV PYTHONUNBUFFERED=1

# Default command
ENTRYPOINT ["word_mcp_server"]
