# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# syntax=docker/dockerfile:1

# Use official Python runtime
FROM python:3.11-slim

# Set working directory
WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

# Copy only requirements first to leverage Docker cache
COPY pyproject.toml README.md ./

# Install Python dependencies first
RUN pip install --no-cache-dir fastapi uvicorn python-multipart boto3

# Copy the rest of the application
COPY . .

# Install the package in development mode with all dependencies
RUN pip install --no-cache-dir -e .

# Expose the default port
EXPOSE 8080

# Set default environment variables
ENV MCP_PORT=8080
ENV MCP_HOST=0.0.0.0
ENV MCP_TRANSPORT=streamable-http

# Start the server using shell form to allow variable substitution
CMD uvicorn word_document_server.main:app --host $MCP_HOST --port $MCP_PORT